[package]
name = "amanda"
version = "0.1.0"
edition = "2024"

[dependencies]
amanda-aicore = { version = "0.1.0", path = "../amanda-aicore" }
amanda-lowiq = { version = "0.1.0", path = "../amanda-lowiq" }
amanda-shared = { version = "0.1.0", path = "../amanda-shared" }
amanda-tools-hyprland = { version = "0.1.0", path = "../amanda-tools-hyprland" }
amanda-tools-standard = { version = "0.1.0", path = "../amanda-tools-standard" }
serde = { version = "1.0.228", features = ["derive"] }
standard_paths = "2.1.0"
toml = "0.9.7"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
